### ISSUE TITLE
Disruptive Idea

### ISSUE THREAD

**Issue by vherrera96** [JuanSaldana/100-days-of-code-challenges#2]
A groundbreaking repo for self-learning python! Thanks a lot, @JuanSaldana. 
Just one issue there are like 99 days missing... It'd be awesome to have challenges besides Day 18.
Cheers!

Victor H. Herrera

**Comment by JuanSaldana** [comment]
Victor,
 u r more than welcome to include the missing 99 days! The repo is public and i will be more than pleased to review you contributions :)
